### ISSUE TITLE
'QListView' object has no attribute 'horizontalHeader'

### ISSUE THREAD

**Issue by SanskritFritz** [tarmack/Pythagora#12]
This is what I get when I run latest pythagora:

mpdunicode: Using python-mpd version 3.0 or later.
Traceback (most recent call last):
  File "pythagora", line 558, in <module>
    main()
  File "pythagora", line 78, in main
    view = Manager(app)
  File "pythagora", line 99, in **init**
    self.view = MainWindow.View(self.config, self.mpdclient, self.library, app)
  File "/usr/share/Pythagora/MainWindow.py", line 66, in **init**
    self.currentList = CurrentPlaylistForm.CurrentPlaylistForm(self, self.app, self.mpdclient, self.library, self.config)
  File "/usr/share/Pythagora/CurrentPlaylistForm.py", line 63, in **init**
    self.currentList.horizontalHeader().setResizeMode(1)
AttributeError: 'QListView' object has no attribute 'horizontalHeader'

**Comment by tarmack** [comment]
Could it be that you use the Qt version (no KDE). I seem to keep forgetting to update those ui files whenever I change something.

Working on the fix right now.

**Comment by tarmack** [comment]
The last commit fixes the issue. Thank you for reporting this error.

**Comment by SanskritFritz** [comment]
Confirmed fixed, thank you.
