### ISSUE TITLE
Problem executing

### ISSUE THREAD

**Issue by ghost** [tarmack/Pythagora#14]
Thanks for the fine gift.

On a pure Qt environment (Ubuntu minimal 12.10 + Fluxbox), if I cd into the extracted Pythagora archive and enter "./pythagora" everything's fine (all the icons appear), but if I launch it by Fluxbox menu ––[exec](Pythagora) {/home/burak/Pythagora/pythagora}–– icons dissappear. My icon theme is Oxygen. Can you help?

**Comment by tarmack** [comment]
Sorry for the late reply, I was very bussy and did not have time for my projects.

This issue probably stems from a working dir issue. I made Pythagora cd into the containing directory.

Please let me know if this solves your issue.
