### ISSUE TITLE
Crash with QT4.7 and KDE4.5

### ISSUE THREAD

**Issue by wodka** [tarmack/Pythagora#3]
Pythagora(13516)/ KSharedDataCache::Private::mapSharedMemory: Opening cache "/var/tmp/kdecache-wodka/icon-cache.kcache" page size is 4096
Pythagora(13516)/ KSharedDataCache::Private::mapSharedMemory: Attached to cache, determining if it must be initialized
Pythagora(13516)/ KSharedDataCache::Private::mapSharedMemory: Cache fully initialized -- attached to memory mapping
Pythagora(13516)/ KSharedDataCache::Private::mapSharedMemory: 4440064 bytes available out of 10485760
Traceback (most recent call last):
  File "pythagora", line 434, in <module>
    main()
  File "pythagora", line 51, in main
    view = Manager(app)
  File "pythagora", line 70, in **init**
    MainWindow.View.**init**(self, self.config, self.mpdclient, app)
  File "/home/wodka/Downloads/tarmack-Pythagora-060c993/MainWindow.py", line 71, in **init**
    self.createViews()
  File "/home/wodka/Downloads/tarmack-Pythagora-060c993/MainWindow.py", line 163, in createViews
    self.currentList = CurrentPlaylistForm.CurrentPlaylistForm(self.view, self.app, self.mpdclient, self.config)
  File "/home/wodka/Downloads/tarmack-Pythagora-060c993/CurrentPlaylistForm.py", line 84, in **init**
    view.connect(self.view.currentList,SIGNAL('indexesMoved(constQModelIndexList&)'),doprint)
TypeError: type 'constQModelIndexList&' is not supported as a slot argument type

**Comment by wodka** [comment]
I just changed line 84 to:
view.connect(self.view.currentList,SIGNAL('indexesMoved()'),doprint)

now it works, but I have no clue whether this will cause other errors

**Comment by tarmack** [comment]
This line is only used for debugging. It can be ommited without any trouble.
I deleted the offending line in the latest commit.
