### ISSUE TITLE
XML parsing error with Shoutcast

### ISSUE THREAD

**Issue by mikeshutlar** [tarmack/Pythagora#5]
Thanks for sorting the python-mpd issue so quickly - have got Pythagora running now (& liking it), but found a small problem: the Shoutcast genre list is empty, and pressing the Reload button causes the following:

```
Traceback (most recent call last):
  File "/usr/share/Pythagora/plugins/ShoutcastForm.py", line 101, in __loadGenres
    genrelist = self.client.getGenereList()
  File "/usr/share/Pythagora/shoutcast.py", line 46, in getGenereList
    xml = ET.XML(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1283, in XML
    return parser.close()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1636, in close
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1488, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

If it's referring to the shoutcast-bookmarks.xml file, this is the current contents:
    <?xml version='1.0' encoding='UTF-8'?>
    <bookmarks><stations /></bookmarks>

Cheers once again :)

**Comment by tarmack** [comment]
Thank you for reporting your issues and help improve Pythagora.

This error seems to refer to the shoutcast genre list that is downloaded trough their API. It might have changed. I'll have a look at it later today.

**Comment by tarmack** [comment]
Apperently Shoutcast has given their API a major update. It looks realy promising :).

It will take some more time to fix this I'm afraid. I might even redesign the Shoutcast plugin. Stay tuned.

**Comment by tarmack** [comment]
Bad news, AOL has put an OSS ban in the license to use the ShoutCast api. I'll be looking for alternatives.

**Comment by mikeshutlar** [comment]
That's annoying, thanks anyway. Icecast is a good alternative, the directory is at http://dir.xiph.org/ with the downloadable listing at http://dir.xiph.org/yp.xml (however, it currently only lists 1000 streams rather than all, see http://icecast.imux.net/viewtopic.php?t=7669)

**Comment by tarmack** [comment]
Great news, ShoutCast is back :)
Pythagora now embeds thier website and catches the playlist urls.

Enjoy

**Comment by mikeshutlar** [comment]
Ha, that's an excellent idea, and it works great - cheers!
