### ISSUE TITLE
ShoutcastForm.py - 'QEvent' is not defined

### ISSUE THREAD

**Issue by mikeshutlar** [tarmack/Pythagora#6]
Hi again,

Using latest revision, the Shoutcast browser part isn't showing, and the following error is displayed in the console:
    Traceback (most recent call last):
      File "/usr/share/Pythagora/plugins/ShoutcastForm.py", line 44, in event
        if event.type() == QEvent.Paint:
    NameError: global name 'QEvent' is not defined

Adding QEvent to the end of:
    from PyQt4.QtCore import SIGNAL, Qt, QUrl, QDateTime
fixes it.

Cheers :)

**Comment by tarmack** [comment]
Thanks for your feedback. Apparantly I forgot to place that line in the last commit. It is fixed now.
